{% set version = "1.5.0" %}

package:
  name: djangocms-admin-style
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangocms-admin-style/djangocms-admin-style-{{ version }}.tar.gz
  sha256: 47d9868aa448e593ce90059d6542a4d907c120d357cd0561c586f5557e3ba316

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - djangocms_admin_style

about:
  home: http://www.django-cms.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Adds pretty CSS styles for the django CMS admin interface'

extra:
  recipe-maintainers:
    - ocefpaf
