{% set name = "djangocms-admin-style" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangocms-admin-style-{{ version }}.tar.gz
  sha256: 26cb361907d5b0d8fb08547129ac04711db2e04ca8bda8d11848633760d52a89

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - djangocms_admin_style
    - djangocms_admin_style.templatetags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/divio/djangocms-admin-style
  summary: Adds pretty CSS styles for the django CMS admin interface.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
