{% set version = "2.0.0" %}

package:
  name: djangocms-admin-style
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangocms-admin-style/djangocms-admin-style-{{ version }}.tar.gz
  sha256: 080f55fe2b643cf608ee8feeb1407bf20e1e76c0f2c058a1bf360b4aa0c90cf4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - djangocms_admin_style

about:
  home: http://www.django-cms.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Adds pretty CSS styles for the django CMS admin interface

extra:
  recipe-maintainers:
    - ocefpaf
