{% set version = "2.0.1" %}

package:
  name: djangocms-admin-style
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangocms-admin-style/djangocms-admin-style-{{ version }}.tar.gz
  sha256: a73f969459cc5d70f47cea0e4c1dd6ef11c18175efcc4f357d1aaaa7eba794fe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - djangocms_admin_style

about:
  home: http://www.django-cms.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Adds pretty CSS styles for the django CMS admin interface

extra:
  recipe-maintainers:
    - ocefpaf
