{% set name = "djangocms-admin-style" %}
{% set version = "3.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djangocms-admin-style-{{ version }}.tar.gz
  sha256: f093c65c92db09713726d71280ecea602d5f348c9ad3b02281f7af245a0598db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - django
    - python >=3.7

test:
  imports:
    - djangocms_admin_style
    - djangocms_admin_style.templatetags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/divio/djangocms-admin-style
  summary: Adds pretty CSS styles for the django CMS admin interface.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
