{% set version = "1.4.0" %}

package:
  name: djangocms-admin-style
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangocms-admin-style/djangocms-admin-style-{{ version }}.tar.gz
  sha256: 0ff3f45ed56e98c92fcabf219377f4165ab20a4cb2d018c1da461b6b85179177

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - djangocms_admin_style

about:
  home: http://www.django-cms.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Adds pretty CSS styles for the django CMS admin interface'

extra:
  recipe-maintainers:
    - ocefpaf
