{% set version = "1.3.0" %}

package:
  name: djangocms-admin-style
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangocms-admin-style/djangocms-admin-style-{{ version }}.tar.gz
  sha256: 18f67fa70442458a7c86f7886c866ddc69fe552ca156c76e8181300ec8fc54e0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - djangocms_admin_style

about:
  home: http://www.django-cms.org/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Adds pretty CSS styles for the django CMS admin interface'

extra:
  recipe-maintainers:
    - ocefpaf
