{% set version = "1.2.7" %}

package:
  name: djangocms-admin-style
  version: {{ version }}

source:
  fn: djangocms-admin-style-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/djangocms-admin-style/djangocms-admin-style-{{ version }}.tar.gz
  sha256: 59dfe4ac535d6377e010c2e1b5e0dd5296b6177ef38e600d12ce8f19ff11e91f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - djangocms_admin_style

about:
  home: http://www.django-cms.org/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Adds pretty CSS styles for the django CMS admin interface.'

extra:
  recipe-maintainers:
    - ocefpaf
