travis:
  secure:
    BINSTAR_TOKEN: oivA59dFWWvCcYaObjNJpkoPvFDs5KZuTwezvsHKVTAe441zWVpgXWeYDlMw7Wk3vEXL5DwmTcKv3Dlk3Zv3bvPctU21d3lWVNrFRjCycn0g4j4aL+d4vZrSmk9qk62aSKuAGJz8S8K8CAMS3TSsQ+xOq8CDxkykIFD76NeSmeOkNVo3Xpu3zA9JPq5SdURx1Pac3Bm19AJxlppeCGOhpnQ1uxdN6c97w8wkHp4FxIaE8U9wHUHHcdi3PFU03XrAdB3wyHgoJb12/8tMa2Ak9jAUnwr5+O2VP5xsq2OPAH6QyZ0RNBLlfSs9W357WZtTYM8FyVhakhMTDimz93EeLNNkr18CURdxb+F8jayLk8Lz+ZUAprtVlA12fg31j8i7PwM93QnFuy/5n4WdywUJNFg19uClusXwVGiCoYWxol8CGpoyA4jZaFKZz6n8hyhAt97dwitp5COEQnHQvD9lNcY7uWkBVEele43/xNaTllqG+wEMoW7qITRr7G6rUh66cumefPFyOgSgYmSEFc7lVIy6K6yXSeZeLXno5UatQfEj/4sjJESTtQRrrzDQsOSvgwdXTSUvQGqWe+EHUv+IVkHJS5+Zp/31aQySl0H+FaomkGvAdKdoIewMHqgrr7UoWeGyOXwsfcT1jkBdzwRjrP3/aMF9R26sgtit8Fw2gLE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
