travis:
  secure:
    BINSTAR_TOKEN: vBJviz1jhY8Q+TNFOqmAeNunNXpNXEgekTJTPJFmPVu1XJp8XqDaPMVMQvEaCOBLMNp+Kh6tgEatsIjpFSXWtgT8w2AMo1wZcrfo3JnnppdDgWk1pbpECRsO4X76mFYZEqe1b+5cq4ycCQfbVUQ9MOlxaDLyOIeGiiG+eI0VsUr5FeHbam90GDGDa4A6n3H0qmQbqrtWdp/JDIMR6My+HgHcJQWTX2+OTCEQkgG5P8bzCHAxt6RKivseDHKNvujNsmLHE9kxeSJj5VPAqP/mPqJrtrTdE+MbQ1WGXhfbb88U0Xlhs4ikVeEJ4XprJId2ZODKtFLBhq4+ivwXGX36PNfcxZo73M5anTP05G9PDEqCmjEhDLp/orErdOQD33BX80xmdIGHs674zRS2iwOoXpQ+H1HOJISViv3lsQTToDiAI3SNtts/IHvGK3BmGCrK/qx73bpWIfTn0pyiPrwisPmUvGo/bx3iD/21oyqUymvd3ASKYMWEyP3h2zXharwCty+rCgLFCLS1c1m1JGFubiMHsI03+hZpzncpnWvyn2gaW+3H9JTRt2m3G1i9XOB8QyoVjg2kDtsh7hJcsDZXKMONrFK8WbB5LlfGoWlZ1yX1ulv5EpnKNAIM0nIlJkfubf0+bZoQ5wJXqWiag2yzzEcE8QWltT56VKI7sXPfhaA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
